### ISSUE TITLE
profile routing hook is being triggered inappropriately?

### ISSUE THREAD

**Issue by propertunist** [iionly/private_profiles#4] opened 2017-04-05 15:58 UTC
i just noticed that if i view a user profile while the private_profiles plugin is active and then click the option on my site to add a new blog (or bookmark or other entity type) - when the 'add new blog' page renders, i see a warning: "There's no member with this name.".
i found that this string is only in private_profiles and it is only triggered when the router can't find a user with the name in the current page's URL. since the 'add new blog' page doesn't have a username in it, the message is triggered. 
the issue here appears to be that the private_profiles router function is being triggered when it should not be.

**Comment by iionly** [comment] 2017-04-05 18:13
> and then click the option on my site to add a new blog

If I understand you correctly that you have some plugin / theme that adds the functionality to add content directly from profile pages, i.e. some non-Elgg core feature? If that's the case, what's this plugin's name? Right now I can't reproduce the issue as the private profile plugin would only take action on profile pages and I don't have any option to directly add any content from there.

**Comment by propertunist** [comment] 2017-04-05 18:53
sure, yes - it is the 'add new items' plugin. i didn't link to it because it is very simple and just adds a popup menu to the topbar that contains hyperlinks to the various 'add new item' pages for plugins. you can see it here: https://elgg.org/plugins/1301890

**Comment by iionly** [comment] 2017-04-07 17:52
I think there's some Elgg core bug responsible.

The Private Profiles plugin uses the route:rewrite plugin hook to check for urls with "profiles" identifier if access to the corresponding profile page of a user it to be granted or denied.

But something goes wrong with the Add New Item plugin in use when selecting one of the menu items for being forwarded to one of the add forms. None of these urls has the "profile" identifier and therefore the route:rewrite callback function of the Private Profiles plugin shouldn't be called at all. Nevertheless, it does get called with a nonsense url, e.g. in case of blogs the url would be site.url/profile/blog/add/<userid>. And of course this goes wrong!

I don't see any way of fixing this within the code of the Private Profiles plugin. The wrongly added "profile" identifier can't be simply ignored as it's strictly spreaking the correct identifier to be expected for the "route:rewrite", "profile" hook. I think it's necessary to fix this in Elgg core code.

I guess I need to open an issue in the Elgg repo about it. Maybe the problem occurs only due to the way the child menu items are added in your plugin. Not sure if it would work when registering using Elgg API funtions (e.g. like in more menu).

**Comment by propertunist** [comment] 2017-04-07 18:06
ok, understood. this issue is only a minor one in comparison to the other issue i opened, that might also end up being an elgg bug.

**Comment by iionly** [comment] 2017-04-09 18:07
I've opened an issue at https://github.com/Elgg/Elgg/issues/10883 about it. But it might be something you might need to fix in your Add New Items plugin by handling the menu item registration / building the menu differently - or at least try if you can do it differently without getting the error message.

**Comment by iionly** [comment] 2017-04-09 18:48
Closing the issue here then.

**Closed by iionly** 2017-04-09 18:48 UTC
